Update TestTerra.yml

diff --git a/.github/workflows/TestTerra.yml b/.github/workflows/TestTerra.yml
--- a/.github/workflows/TestTerra.yml
+++ b/.github/workflows/TestTerra.yml
@@ -6,7 +6,7 @@ jobs:
   Planning-Stage:
     runs-on: ubuntu-latest
     env:
-      versionCoreData: '10,12'
+      versionCoreData: '10='
 
     steps:
       - name: Checkout Repo
@@ -19,5 +19,11 @@ jobs:
             echo "$versionCoreArray"
             if [ "${#versionCoreArray[@]}" -gt 1 ]; then
               echo "Error in deriving terraform minimum required version. Got more than one required_version configuration from terraform deployment source : ${versionCoreArray[@]}. Please keep only one required_version configuration."
+              exit 1
+            else
+              firstVersionVersionConstraint = "${versionCoreArray[0]}"
+              version = $(echo $firstVersionVersionConstraint | sed -E 's/[=|!|>|<|~ ]+//g')
+              echo "Terraform minimum required version derived from terraform deployment source's required_version : $version"
+            fi
             fi
           fi
